### GENERAL SETTINGS ###

# Site settings
title: Kernels
description: "Kernels: Jupyter Notebook client for iPad"
analytics: UA-104527683-1
baseurl: 
url: "//kernels.io"
image: "assets/img/screenshot_cut.png"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#418ffa" #"#F70031"
  primary_gradient: "#2a4ed6" #"#F70031"
  primary_rgb: "65,143,250" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

twitter:
  username: kernels_io

logo:

social:
  name: Kernels
  links:
    - https://twitter.com/kernels_io
    - https://github.com/navoshta

webmaster_verifications:
  google: XkeGdxyWFoVT7ROPa1di7i4eGi_Pftw9YxQlaspQY3g
  bing: B3662597D7C2123E3EA94C06277B091D
  yandex: 40577c77a6506097

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: contact@kernels.io

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We believe developers and researchers deserve better tools — so we built Kernels, a Jupyter Notebook client for iPad. Kernels lets you connect to a remote server running Jupyter Notebook and use it on-the-go."

author: "Kernels"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap