### GENERAL SETTINGS ###

# Site settings
title: Kernels
description: "Kernels: a Jupyter Notebook client for iPad. Connect to a notebook server and do everything you do on desktop, anywhere."
analytics: UA-104527683-1
baseurl: 
url: "//kernels.io"
image: assets/img/screenshot_cut.png

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> 

colors:  #in hex code if not noted else
  primary: "#E76817" 
  blog_heading: "#E6A14A"
  primary_gradient_top: "#EA802C"
  primary_gradient_bottom: "#EBAF53"
  primary_rgb: "230,111,25" # We use RGB value here since it's needed in some places for the transparency effect.
  secondary: "#2E2A2A"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

twitter:
  username: kernels_io

logo: /assets/img/logo.png
about: "We believe developers and researchers deserve better tools, so that they can focus on building new exciting things. That is why we have made Kernels, a Jupyter Notebook client for iPad. Kernels lets you connect to a notebook server and do everything you do on desktop, anywhere."
author: "Alex Staravoitau"
lang: "en_GB"

email: contact@kernels.io

social:
  name: Kernels
  links:
    - https://twitter.com/kernels_io

webmaster_verifications:
  google: XkeGdxyWFoVT7ROPa1di7i4eGi_Pftw9YxQlaspQY3g
  bing: B3662597D7C2123E3EA94C06277B091D
  yandex: 40577c77a6506097

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.png