### GENERAL SETTINGS ###

# Site settings
title: Juno
description: "Juno: iOS Jupyter client for iPhone and iPad. Connect to a notebook server with Juno and do everything you do on desktop, anywhere."
analytics: UA-104527683-1
baseurl: 
url: "//juno.sh"
image: assets/img/screenshot_cut.png

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> 

# Syntax highlighting
highlighter: rouge
kramdown:
    input: GFM 
    syntax_highlighter: rouge

colors:  #in hex code if not noted else
  primary: "#E76817" 
  blog_heading: "#E6A14A"
  primary_gradient_top: "#EA802C"
  primary_gradient_bottom: "#EBAF53"
  primary_rgb: "230,111,25" # We use RGB value here since it's needed in some places for the transparency effect.
  secondary: "#2E2A2A"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

twitter:
  username: junoclient

logo: /assets/img/logo.png
about: "Connect to a Jupyter/IPython server with Juno and do everything you do on desktop, anywhere. Sign up for beta now!"
author: "Alex Staravoitau"
lang: "en_GB"

email: contact@juno.sh

social:
  name: Juno
  links:
    - https://twitter.com/junoclient

webmaster_verifications:
  google: XkeGdxyWFoVT7ROPa1di7i4eGi_Pftw9YxQlaspQY3g
  bing: B3662597D7C2123E3EA94C06277B091D
  yandex: 40577c77a6506097

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.png

screenshots_tablet:
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_01.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_01_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_02.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_02_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_03.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_03_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_04.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_04_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_05.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_05_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_06.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_06_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_07.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_07_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_08.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_08_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_09.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_09_thumb@2x.png
  - src: /assets/img/screenshots/tablet/screenshot_v_tablet_10.png
    thumb: /assets/img/screenshots/tablet/screenshot_v_tablet_10_thumb@2x.png

screenshots_phone:
  - src: /assets/img/screenshots/phone/screenshot_v_phone_01.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_01_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_02.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_02_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_03.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_03_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_04.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_04_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_05.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_05_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_06.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_06_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_07.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_07_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_08.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_08_thumb@2x.png
  - src: /assets/img/screenshots/phone/screenshot_v_phone_09.png
    thumb: /assets/img/screenshots/phone/screenshot_v_phone_09_thumb@2x.png

